name: Generate PR Report

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository in owner/repo format'
        required: true
        type: string
      start_date:
        description: 'Start date (inclusive) in YYYY-MM-DD format'
        required: true
        type: string
      end_date:
        description: 'End date (inclusive) in YYYY-MM-DD format'
        required: true
        type: string
      output_file:
        description: 'Output JSON file name'
        required: false
        default: 'prs.json'
        type: string

jobs:
  generate-report:
    runs-on: buildjet-2vcpu-ubuntu-2204
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run PR Reporter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python pr_reporter.py "${{ github.event.inputs.repository }}" \
            "${{ github.event.inputs.start_date }}" \
            "${{ github.event.inputs.end_date }}" \
            --output "${{ github.event.inputs.output_file }}"

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: pr-report
          path: ${{ github.event.inputs.output_file }}
